#!/bin/bash
echo "开始进行批量修改文件名字"
if [ $# -eq 1 ]
then
    python /home/huyang/Document/python-project/rename.py $1
elif [ $# -eq 2 ]
then
    python /home/huyang/Document/python-project/rename.py $1 $2
else
    echo "参数数量不匹配"
fi
